// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/openshift/api/pcap/v1/generated.proto

package v1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"

	k8s_io_api_core_v1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *PCAP) Reset()      { *m = PCAP{} }
func (*PCAP) ProtoMessage() {}
func (*PCAP) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b469f0954bff08, []int{0}
}
func (m *PCAP) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PCAP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PCAP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCAP.Merge(m, src)
}
func (m *PCAP) XXX_Size() int {
	return m.Size()
}
func (m *PCAP) XXX_DiscardUnknown() {
	xxx_messageInfo_PCAP.DiscardUnknown(m)
}

var xxx_messageInfo_PCAP proto.InternalMessageInfo

func (m *PCAPDestination) Reset()      { *m = PCAPDestination{} }
func (*PCAPDestination) ProtoMessage() {}
func (*PCAPDestination) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b469f0954bff08, []int{1}
}
func (m *PCAPDestination) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PCAPDestination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PCAPDestination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCAPDestination.Merge(m, src)
}
func (m *PCAPDestination) XXX_Size() int {
	return m.Size()
}
func (m *PCAPDestination) XXX_DiscardUnknown() {
	xxx_messageInfo_PCAPDestination.DiscardUnknown(m)
}

var xxx_messageInfo_PCAPDestination proto.InternalMessageInfo

func (m *PCAPList) Reset()      { *m = PCAPList{} }
func (*PCAPList) ProtoMessage() {}
func (*PCAPList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b469f0954bff08, []int{2}
}
func (m *PCAPList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PCAPList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PCAPList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCAPList.Merge(m, src)
}
func (m *PCAPList) XXX_Size() int {
	return m.Size()
}
func (m *PCAPList) XXX_DiscardUnknown() {
	xxx_messageInfo_PCAPList.DiscardUnknown(m)
}

var xxx_messageInfo_PCAPList proto.InternalMessageInfo

func (m *PCAPSource) Reset()      { *m = PCAPSource{} }
func (*PCAPSource) ProtoMessage() {}
func (*PCAPSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b469f0954bff08, []int{3}
}
func (m *PCAPSource) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PCAPSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PCAPSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCAPSource.Merge(m, src)
}
func (m *PCAPSource) XXX_Size() int {
	return m.Size()
}
func (m *PCAPSource) XXX_DiscardUnknown() {
	xxx_messageInfo_PCAPSource.DiscardUnknown(m)
}

var xxx_messageInfo_PCAPSource proto.InternalMessageInfo

func (m *PCAPSpec) Reset()      { *m = PCAPSpec{} }
func (*PCAPSpec) ProtoMessage() {}
func (*PCAPSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b469f0954bff08, []int{4}
}
func (m *PCAPSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PCAPSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PCAPSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCAPSpec.Merge(m, src)
}
func (m *PCAPSpec) XXX_Size() int {
	return m.Size()
}
func (m *PCAPSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PCAPSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PCAPSpec proto.InternalMessageInfo

func (m *PCAPStatus) Reset()      { *m = PCAPStatus{} }
func (*PCAPStatus) ProtoMessage() {}
func (*PCAPStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b469f0954bff08, []int{5}
}
func (m *PCAPStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PCAPStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PCAPStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCAPStatus.Merge(m, src)
}
func (m *PCAPStatus) XXX_Size() int {
	return m.Size()
}
func (m *PCAPStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PCAPStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PCAPStatus proto.InternalMessageInfo

func (m *Trace) Reset()      { *m = Trace{} }
func (*Trace) ProtoMessage() {}
func (*Trace) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b469f0954bff08, []int{6}
}
func (m *Trace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Trace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Trace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trace.Merge(m, src)
}
func (m *Trace) XXX_Size() int {
	return m.Size()
}
func (m *Trace) XXX_DiscardUnknown() {
	xxx_messageInfo_Trace.DiscardUnknown(m)
}

var xxx_messageInfo_Trace proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PCAP)(nil), "github.com.openshift.api.pcap.v1.PCAP")
	proto.RegisterType((*PCAPDestination)(nil), "github.com.openshift.api.pcap.v1.PCAPDestination")
	proto.RegisterType((*PCAPList)(nil), "github.com.openshift.api.pcap.v1.PCAPList")
	proto.RegisterType((*PCAPSource)(nil), "github.com.openshift.api.pcap.v1.PCAPSource")
	proto.RegisterType((*PCAPSpec)(nil), "github.com.openshift.api.pcap.v1.PCAPSpec")
	proto.RegisterType((*PCAPStatus)(nil), "github.com.openshift.api.pcap.v1.PCAPStatus")
	proto.RegisterType((*Trace)(nil), "github.com.openshift.api.pcap.v1.Trace")
}

func init() {
	proto.RegisterFile("github.com/openshift/api/pcap/v1/generated.proto", fileDescriptor_c6b469f0954bff08)
}

var fileDescriptor_c6b469f0954bff08 = []byte{
	// 818 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcf, 0x6f, 0x1c, 0x35,
	0x14, 0xde, 0x99, 0xdd, 0x4d, 0x76, 0xbd, 0x94, 0x82, 0x01, 0xb1, 0x0a, 0x30, 0x89, 0xe6, 0x50,
	0xa2, 0x52, 0x3c, 0xdd, 0xf2, 0x43, 0xbd, 0x32, 0xed, 0x25, 0x6a, 0x69, 0x57, 0x26, 0x27, 0xe0,
	0x80, 0xe3, 0x71, 0x76, 0x4d, 0x98, 0xb1, 0x35, 0xf6, 0x46, 0xe2, 0x82, 0xf8, 0x03, 0x38, 0xf0,
	0xcf, 0x20, 0xee, 0x9c, 0x22, 0x4e, 0x3d, 0xf6, 0x14, 0x91, 0x45, 0xe2, 0x8f, 0xe0, 0x84, 0xfc,
	0xc6, 0xf3, 0x83, 0xa6, 0xd5, 0xee, 0x6d, 0xde, 0x7b, 0xdf, 0xf7, 0x3d, 0xfb, 0xbd, 0x6f, 0x8c,
	0xee, 0x2e, 0xa4, 0x5d, 0xae, 0x4e, 0x08, 0x57, 0x79, 0xa2, 0xb4, 0x28, 0xcc, 0x52, 0x9e, 0xda,
	0x84, 0x69, 0x99, 0x68, 0xce, 0x74, 0x72, 0x3e, 0x4b, 0x16, 0xa2, 0x10, 0x25, 0xb3, 0x22, 0x23,
	0xba, 0x54, 0x56, 0xe1, 0x83, 0x96, 0x41, 0x1a, 0x06, 0x61, 0x5a, 0x12, 0xc7, 0x20, 0xe7, 0xb3,
	0xbd, 0x8f, 0x3b, 0x9a, 0x0b, 0xb5, 0x50, 0x09, 0x10, 0x4f, 0x56, 0xa7, 0x10, 0x41, 0x00, 0x5f,
	0x95, 0xe0, 0x5e, 0x7c, 0x76, 0xdf, 0x10, 0xa9, 0xa0, 0x29, 0x57, 0xa5, 0x78, 0x49, 0xd3, 0xbd,
	0x4f, 0x5b, 0x4c, 0xce, 0xf8, 0x52, 0x16, 0xa2, 0xfc, 0x31, 0xd1, 0x67, 0x0b, 0x97, 0x30, 0x49,
	0x2e, 0x2c, 0x7b, 0x19, 0x2b, 0x79, 0x15, 0xab, 0x5c, 0x15, 0x56, 0xe6, 0xe2, 0x1a, 0xe1, 0xf3,
	0x4d, 0x04, 0xc3, 0x97, 0x22, 0x67, 0x2f, 0xf2, 0xe2, 0x5f, 0x42, 0x34, 0x98, 0x3f, 0xf8, 0x62,
	0x8e, 0xbf, 0x43, 0x23, 0x77, 0x98, 0x8c, 0x59, 0x36, 0x0d, 0x0e, 0x82, 0xc3, 0xc9, 0xbd, 0xbb,
	0xa4, 0xd2, 0x24, 0x5d, 0x4d, 0xa2, 0xcf, 0x16, 0x2e, 0x61, 0x88, 0x43, 0x93, 0xf3, 0x19, 0x79,
	0x7a, 0xf2, 0xbd, 0xe0, 0xf6, 0x4b, 0x61, 0x59, 0x8a, 0x2f, 0x2e, 0xf7, 0x7b, 0xeb, 0xcb, 0x7d,
	0xd4, 0xe6, 0x68, 0xa3, 0x8a, 0x1f, 0xa3, 0x81, 0xd1, 0x82, 0x4f, 0x43, 0x50, 0xbf, 0x4d, 0x36,
	0x6d, 0x83, 0xb8, 0x73, 0x7d, 0xa5, 0x05, 0x4f, 0x5f, 0xf3, 0xba, 0x03, 0x17, 0x51, 0x50, 0xc1,
	0xc7, 0x68, 0xc7, 0x58, 0x66, 0x57, 0x66, 0xda, 0x07, 0xbd, 0x3b, 0x5b, 0xea, 0x01, 0x27, 0x7d,
	0xdd, 0x2b, 0xee, 0x54, 0x31, 0xf5, 0x5a, 0xf1, 0xef, 0x01, 0xba, 0xe9, 0x60, 0x0f, 0x85, 0xb1,
	0xb2, 0x60, 0x56, 0xaa, 0x02, 0x7f, 0x86, 0x26, 0x59, 0x1b, 0xc2, 0x70, 0xc6, 0xe9, 0x5b, 0x5e,
	0x60, 0xd2, 0x41, 0xd2, 0x2e, 0x0e, 0x1f, 0xa0, 0x81, 0x56, 0xa5, 0x85, 0xeb, 0x0e, 0xdb, 0x2b,
	0xcc, 0x55, 0x69, 0x29, 0x54, 0xf0, 0x23, 0x34, 0x82, 0x25, 0x70, 0xf5, 0x03, 0x5c, 0x62, 0x9c,
	0x26, 0x1e, 0x35, 0x9a, 0xfb, 0xfc, 0xbf, 0x97, 0xfb, 0xef, 0x5d, 0x37, 0x19, 0xa9, 0xcb, 0xb4,
	0x11, 0x88, 0x7f, 0x0b, 0xd0, 0xc8, 0x9d, 0xfc, 0xb1, 0x34, 0x16, 0x7f, 0x7b, 0x6d, 0x99, 0x64,
	0xbb, 0x65, 0x3a, 0x36, 0xac, 0xf2, 0x8d, 0xfa, 0x24, 0x75, 0xa6, 0xb3, 0xc8, 0x47, 0x68, 0x28,
	0xad, 0xc8, 0xcd, 0x34, 0x3c, 0xe8, 0x1f, 0x4e, 0xee, 0xdd, 0xda, 0x6e, 0xf2, 0xe9, 0x0d, 0x2f,
	0x39, 0x3c, 0x72, 0x64, 0x5a, 0x69, 0xc4, 0x3f, 0x21, 0x04, 0x7b, 0x51, 0xab, 0x92, 0x0b, 0x37,
	0xb4, 0x42, 0x65, 0xc2, 0x0f, 0xb9, 0x19, 0xda, 0x13, 0x95, 0x09, 0x0a, 0x15, 0xfc, 0x01, 0xea,
	0x6b, 0x95, 0xc1, 0x54, 0xc7, 0xe9, 0xc4, 0x03, 0xfa, 0x73, 0x95, 0x51, 0x97, 0xc7, 0x09, 0x1a,
	0x17, 0x2c, 0x17, 0x46, 0x33, 0x2e, 0xfc, 0x50, 0xdf, 0xf4, 0xa0, 0xf1, 0x93, 0xba, 0x40, 0x5b,
	0x4c, 0xfc, 0x8f, 0x9f, 0x9b, 0xb3, 0x16, 0xde, 0x43, 0xa1, 0xcc, 0x7c, 0x73, 0xe4, 0x69, 0xe1,
	0xd1, 0x43, 0x1a, 0xca, 0x0c, 0x0c, 0x07, 0x87, 0xf4, 0x06, 0xde, 0xd6, 0x70, 0xc0, 0xe9, 0x18,
	0x0e, 0x62, 0xea, 0xb5, 0xf0, 0xf2, 0xff, 0xe6, 0xaa, 0xbc, 0x3c, 0xdb, 0x4e, 0xba, 0x63, 0xbd,
	0xcd, 0x7e, 0x8c, 0xff, 0x08, 0xfc, 0xa4, 0xc1, 0xe9, 0xf8, 0x29, 0xda, 0xb1, 0x25, 0xe3, 0xc2,
	0x4c, 0x03, 0xd8, 0xe2, 0x87, 0x9b, 0x7b, 0x1e, 0x3b, 0x7c, 0x7b, 0x13, 0x08, 0x0d, 0xf5, 0x32,
	0x98, 0x23, 0xc4, 0x55, 0x91, 0x49, 0xd7, 0xac, 0xb6, 0x46, 0xb2, 0x9d, 0xeb, 0x1e, 0xd4, 0xbc,
	0xf6, 0x05, 0x69, 0x52, 0x86, 0x76, 0x64, 0xe3, 0x3f, 0xfb, 0x68, 0x08, 0x7d, 0xf1, 0x37, 0x68,
	0xec, 0xde, 0x35, 0x63, 0x59, 0xae, 0xbd, 0xc7, 0x6f, 0x6f, 0xd7, 0xed, 0x58, 0xe6, 0xa2, 0x35,
	0xc5, 0x71, 0x2d, 0x42, 0x5b, 0xbd, 0xc6, 0x86, 0xe1, 0x26, 0x1b, 0xf6, 0x5f, 0x61, 0xc3, 0x4f,
	0xd0, 0xc8, 0x94, 0x5c, 0x9e, 0x3a, 0x17, 0x0e, 0x00, 0xf3, 0xae, 0xc7, 0xdc, 0xac, 0x0c, 0x70,
	0x54, 0x58, 0x51, 0xba, 0x32, 0x6d, 0x80, 0xf8, 0x3e, 0x1a, 0x65, 0xc6, 0x56, 0xa4, 0x21, 0x90,
	0xde, 0xf7, 0xa4, 0xb7, 0x3b, 0x5b, 0xed, 0x30, 0x6b, 0x34, 0xbe, 0x85, 0x86, 0x4e, 0x45, 0x4f,
	0x77, 0x80, 0xd6, 0xfc, 0xbc, 0xbe, 0xd7, 0x9c, 0x56, 0x65, 0xfc, 0x11, 0x1a, 0x3a, 0x8e, 0x9e,
	0xee, 0x02, 0xee, 0x1d, 0x8f, 0xbb, 0xd1, 0x95, 0x9f, 0xd3, 0x0a, 0x83, 0xef, 0xa0, 0x5d, 0x53,
	0x72, 0x78, 0xc3, 0x46, 0xf0, 0x86, 0x35, 0xcb, 0xa9, 0x64, 0xe1, 0x25, 0xab, 0x21, 0x78, 0x86,
	0x76, 0x33, 0x63, 0x01, 0x3d, 0x06, 0x74, 0x73, 0xe1, 0x8e, 0x78, 0x45, 0xf1, 0xb8, 0xf4, 0xf0,
	0xe2, 0x2a, 0xea, 0x3d, 0xbb, 0x8a, 0x7a, 0xcf, 0xaf, 0xa2, 0xde, 0xcf, 0xeb, 0x28, 0xb8, 0x58,
	0x47, 0xc1, 0xb3, 0x75, 0x14, 0x3c, 0x5f, 0x47, 0xc1, 0x5f, 0xeb, 0x28, 0xf8, 0xf5, 0xef, 0xa8,
	0xf7, 0x75, 0x78, 0x3e, 0xfb, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x4d, 0x5e, 0x15, 0xec, 0x07,
	0x00, 0x00,
}

func (m *PCAP) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PCAP) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PCAP) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PCAPDestination) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PCAPDestination) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PCAPDestination) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Protocol)
	copy(dAtA[i:], m.Protocol)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Protocol)))
	i--
	dAtA[i] = 0x1a
	i = encodeVarintGenerated(dAtA, i, uint64(m.Port))
	i--
	dAtA[i] = 0x10
	i -= len(m.Destination)
	copy(dAtA[i:], m.Destination)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Destination)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PCAPList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PCAPList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PCAPList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PCAPSource) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PCAPSource) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PCAPSource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Namespace)
	copy(dAtA[i:], m.Namespace)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Namespace)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Pod)
	copy(dAtA[i:], m.Pod)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Pod)))
	i--
	dAtA[i] = 0x12
	i -= len(m.Node)
	copy(dAtA[i:], m.Node)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Node)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PCAPSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PCAPSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PCAPSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Destination.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Source.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	i -= len(m.ID)
	copy(dAtA[i:], m.ID)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ID)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PCAPStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PCAPStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PCAPStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Conditions) > 0 {
		for iNdEx := len(m.Conditions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Conditions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Traces) > 0 {
		for iNdEx := len(m.Traces) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Traces[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Trace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Trace) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Trace) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintGenerated(dAtA, i, uint64(m.DestinationPort))
	i--
	dAtA[i] = 0x48
	i = encodeVarintGenerated(dAtA, i, uint64(m.SourcePort))
	i--
	dAtA[i] = 0x40
	i -= len(m.DestinationIP)
	copy(dAtA[i:], m.DestinationIP)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.DestinationIP)))
	i--
	dAtA[i] = 0x3a
	i -= len(m.SourceIP)
	copy(dAtA[i:], m.SourceIP)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.SourceIP)))
	i--
	dAtA[i] = 0x32
	i -= len(m.DestinationInterface)
	copy(dAtA[i:], m.DestinationInterface)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.DestinationInterface)))
	i--
	dAtA[i] = 0x2a
	i -= len(m.SourceInterface)
	copy(dAtA[i:], m.SourceInterface)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.SourceInterface)))
	i--
	dAtA[i] = 0x22
	i -= len(m.Pod)
	copy(dAtA[i:], m.Pod)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Pod)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Node)
	copy(dAtA[i:], m.Node)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Node)))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Timestamp.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PCAP) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PCAPDestination) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Destination)
	n += 1 + l + sovGenerated(uint64(l))
	n += 1 + sovGenerated(uint64(m.Port))
	l = len(m.Protocol)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PCAPList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PCAPSource) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Node)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Pod)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Namespace)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PCAPSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Source.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Destination.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PCAPStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Traces) > 0 {
		for _, e := range m.Traces {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.Conditions) > 0 {
		for _, e := range m.Conditions {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *Trace) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Timestamp.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Node)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Pod)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.SourceInterface)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.DestinationInterface)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.SourceIP)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.DestinationIP)
	n += 1 + l + sovGenerated(uint64(l))
	n += 1 + sovGenerated(uint64(m.SourcePort))
	n += 1 + sovGenerated(uint64(m.DestinationPort))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *PCAP) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PCAP{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "PCAPSpec", "PCAPSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "PCAPStatus", "PCAPStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PCAPDestination) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PCAPDestination{`,
		`Destination:` + fmt.Sprintf("%v", this.Destination) + `,`,
		`Port:` + fmt.Sprintf("%v", this.Port) + `,`,
		`Protocol:` + fmt.Sprintf("%v", this.Protocol) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PCAPList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]PCAP{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "PCAP", "PCAP", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&PCAPList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *PCAPSource) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PCAPSource{`,
		`Node:` + fmt.Sprintf("%v", this.Node) + `,`,
		`Pod:` + fmt.Sprintf("%v", this.Pod) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PCAPSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PCAPSpec{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`Source:` + strings.Replace(strings.Replace(this.Source.String(), "PCAPSource", "PCAPSource", 1), `&`, ``, 1) + `,`,
		`Destination:` + strings.Replace(strings.Replace(this.Destination.String(), "PCAPDestination", "PCAPDestination", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PCAPStatus) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForTraces := "[]Trace{"
	for _, f := range this.Traces {
		repeatedStringForTraces += strings.Replace(strings.Replace(f.String(), "Trace", "Trace", 1), `&`, ``, 1) + ","
	}
	repeatedStringForTraces += "}"
	repeatedStringForConditions := "[]Condition{"
	for _, f := range this.Conditions {
		repeatedStringForConditions += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForConditions += "}"
	s := strings.Join([]string{`&PCAPStatus{`,
		`Traces:` + repeatedStringForTraces + `,`,
		`Conditions:` + repeatedStringForConditions + `,`,
		`}`,
	}, "")
	return s
}
func (this *Trace) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Trace{`,
		`Timestamp:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Timestamp), "Time", "v1.Time", 1), `&`, ``, 1) + `,`,
		`Node:` + fmt.Sprintf("%v", this.Node) + `,`,
		`Pod:` + fmt.Sprintf("%v", this.Pod) + `,`,
		`SourceInterface:` + fmt.Sprintf("%v", this.SourceInterface) + `,`,
		`DestinationInterface:` + fmt.Sprintf("%v", this.DestinationInterface) + `,`,
		`SourceIP:` + fmt.Sprintf("%v", this.SourceIP) + `,`,
		`DestinationIP:` + fmt.Sprintf("%v", this.DestinationIP) + `,`,
		`SourcePort:` + fmt.Sprintf("%v", this.SourcePort) + `,`,
		`DestinationPort:` + fmt.Sprintf("%v", this.DestinationPort) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *PCAP) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PCAP: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PCAP: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PCAPDestination) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PCAPDestination: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PCAPDestination: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destination = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Protocol = k8s_io_api_core_v1.Protocol(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PCAPList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PCAPList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PCAPList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, PCAP{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PCAPSource) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PCAPSource: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PCAPSource: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Node = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PCAPSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PCAPSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PCAPSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Source.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Destination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PCAPStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PCAPStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PCAPStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Traces", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Traces = append(m.Traces, Trace{})
			if err := m.Traces[len(m.Traces)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conditions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Conditions = append(m.Conditions, v1.Condition{})
			if err := m.Conditions[len(m.Conditions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Trace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Trace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Trace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Timestamp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Node = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceInterface", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceInterface = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationInterface", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationInterface = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceIP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceIP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationIP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationIP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourcePort", wireType)
			}
			m.SourcePort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourcePort |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationPort", wireType)
			}
			m.DestinationPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestinationPort |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
